import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!;
const K=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const R=U.replace(/\/$/,"")+"/rest/v1";
const H={accept:"application/json",apikey:K,Authorization:"Bearer "+K};
async function getJson(url:string){const r=await fetch(url,{headers:{"user-agent":"3D-Earth-Observatory/1.0"}});if(!r.ok)throw Error(url+" -> "+r.status);return r.json();}
async function getText(url:string){const r=await fetch(url,{headers:{"user-agent":"3D-Earth-Observatory/1.0"}});if(!r.ok)throw Error(url+" -> "+r.status);return r.text();}
async function source(slug:string){const r=await fetch(R+"/observatory_sources?slug=eq."+encodeURIComponent(slug)+"&select=id",{headers:H});const a=await r.json();if(!a[0])throw Error("missing source "+slug);return a[0].id;}
async function insert(rows:any[]){if(!rows.length)return 0;for(let i=0;i<rows.length;i+=500){const r=await fetch(R+"/observatory_observations?on_conflict=source_id%2Cexternal_id%2Cobserved_at",{method:"POST",headers:{...H,"content-type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows.slice(i,i+500))});if(!r.ok)throw Error("insert "+r.status+" "+await r.text());}return rows.length;}
function row(s:string,sector:string,id:string,time:string,p:any,metric:string,value:number,unit:string){return {source_id:s,sector,external_id:id,observed_at:time,latitude:null,longitude:null,metric,value,unit,quality_status:"verified",freshness_sla_seconds:sector==="climate"?2592000:sector==="air-quality"?63072000:31536000,payload:p};}
async function climate(){const s=await source("nasa-giss-climate"),txt=await getText("https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.csv"),rows:any[]=[];for(const line of txt.split("\n")){const p=line.trim().split(",");if(p.length<3||!/^\d{4}$/.test(p[0]))continue;const y=Number(p[0]);for(let m=1;m<=12;m++){const v=Number(p[m]);if(Number.isFinite(v))rows.push(row(s,"climate",y+"-"+m,new Date(Date.UTC(y,m-1,15)).toISOString(),{dataset:"GISTEMP v4",year:y,month:m,provider:"NASA GISS"},"global_surface_temperature_anomaly",v,"degC"));}}return insert(rows);}
async function freshwater(){const s=await source("fao-aquastat-freshwater"),codes=["ER.H2O.FWAG.ZS","ER.H2O.FWIN.ZS","ER.H2O.FWDM.ZS","ER.H2O.FWTL.ZS","ER.H2O.FWTL.K3","ER.H2O.INTR.K3","ER.H2O.INTR.PC"],rows:any[]=[];for(const code of codes){const d=await getJson("https://api.worldbank.org/v2/country/all/indicator/"+encodeURIComponent(code)+"?format=json&per_page=20000");const arr=Array.isArray(d)?d[1]||[]:[];for(const x of arr){if(x.value===null||!x.countryiso3code)continue;const y=Number(x.date);if(!Number.isFinite(y))continue;rows.push(row(s,"freshwater",x.countryiso3code+"@"+code+"@"+y,new Date(Date.UTC(y,6,1)).toISOString(),x,x.indicator?.value||code,Number(x.value),code.endsWith(".ZS")?"percent":code.endsWith(".K3")?"billion_m3":"m3_per_capita"));}}return insert(rows);}
async function air(){const s=await source("world-bank-ihme-air-quality"),codes=["EN.ATM.PM25.MC.M3","EN.ATM.PM25.MC.ZS"],rows:any[]=[];for(const code of codes){const d=await getJson("https://api.worldbank.org/v2/country/all/indicator/"+encodeURIComponent(code)+"?format=json&per_page=20000");const arr=Array.isArray(d)?d[1]||[]:[];for(const x of arr){if(x.value===null||!x.countryiso3code)continue;const y=Number(x.date);if(!Number.isFinite(y))continue;rows.push(row(s,"air-quality",x.countryiso3code+"@"+code+"@"+y,new Date(Date.UTC(y,6,1)).toISOString(),{country:x.country,indicator:x.indicator,source:"World Bank WDI",underlying_methodology:"GBD/IHME"} ,x.indicator?.value||code,Number(x.value),code.endsWith(".ZS")?"percent":"ug/m3"));}}return insert(rows);}async function authorized(req:Request){const supplied=req.headers.get("x-observatory-ingest-token")||"";if(!supplied)return false;const r=await fetch(R+"/observatory_ingest_credentials?active=eq.true&select=token_hash&limit=1",{headers:H});if(!r.ok)return false;const a=await r.json();if(!a[0]?.token_hash)return false;const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(supplied)))).map(x=>x.toString(16).padStart(2,"0")).join("");return hash===a[0].token_hash;}
Deno.serve(async req=>{if(!(await authorized(req)))return new Response(JSON.stringify({error:"unauthorized"}),{status:401});if(req.method!=="POST")return new Response(JSON.stringify({error:"POST required"}),{status:405});const body=await req.json().catch(()=>({})),wanted=new Set(body.sources||["all"]),results:any[]=[];for(const [name,fn] of [["climate",climate],["freshwater",freshwater],["air-quality",air]] as any){if(!wanted.has("all")&&!wanted.has(name))continue;try{results.push({sector:name,records:await fn(),status:"success"});}catch(e){results.push({sector:name,status:"failed",error:String(e)});}}return new Response(JSON.stringify({ok:true,results}),{headers:{"content-type":"application/json"}});});
