const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
test('mobile-first navigation is present across core views',()=>{for(const p of ['index.html','dashboard.html','map.html','about.html','privacy.html','terms.html','data-policy.html']){const h=read(p);assert.match(h,/navigation\.js/);assert.match(h,/mobile-nav\.css/)}})

test('shared navigation defines the canonical core destinations',()=>{const source=read('public/js/navigation.js');for(const href of ['/','/dashboard.html','/satellites.html','/map.html','/about.html','/data-policy.html'])assert.ok(source.includes("'"+href+"'"),href)})
test('dashboard is a real planetary observatory',()=>{const h=read('dashboard.html');assert.match(h,/globe-stage/);assert.match(h,/js\/astronomy\.js/);assert.match(h,/satellite\.js@4\.1\.4/);assert.match(h,/satellite-drawer/);assert.match(h,/locate-globe/);assert.doesNotMatch(h,/osint-dashboard|geo-weather|aoi-tool|intel-overlay|script\.js/)})
test('renderer uses deterministic Earth assets and solar geometry',()=>{const s=read('public/js/globe.js');for(const a of ['earth_atmos_2048.jpg','earth_normal_2048.jpg','earth_specular_2048.jpg','earth_clouds_1024.png','moon_1024.jpg'])assert.match(s,new RegExp(a));assert.doesNotMatch(s,/earth_lights_2048\.png/);assert.match(s,/Promise\.all/);assert.match(s,/SphereGeometry\(1,96,96\)/);assert.match(s,/ShaderMaterial/);assert.match(s,/PlanetAstronomy\.solar/);assert.match(s,/earthPoint\(solar\.subLat,solar\.subLon/)})
test('astronomy module exposes deterministic solar calculations',()=>{const s=read('public/js/astronomy.js');assert.match(s,/function solar/);assert.match(s,/function sunDirection/);assert.match(s,/window\.PlanetAstronomy/)})
test('map is world-first and location is session-private',()=>{const h=read('map.html'),s=read('public/js/map.js');assert.match(h,/OPENSTREETMAP/);assert.match(s,/new ol\.Map/);assert.match(s,/fromLonLat\(WORLD\)/);assert.match(s,/WORLD_ZOOM/);assert.match(s,/enableHighAccuracy: true/);assert.match(s,/sessionStorage/);assert.match(s,/accuracy/)})
test('satellite gateway supports authoritative CelesTrak groups',()=>{const s=read('src/ingest/tle.js'),a=read('src/routes/api.js');for(const g of ['stations','weather','gps-ops','science','starlink'])assert.match(s,new RegExp(g));assert.match(a,/req\.query\.group/);assert.match(a,/source: 'CelesTrak GP'/)})
test('legacy globe implementation is gone',()=>{assert.equal(fs.existsSync(path.join(root,'public/js/script.js')),false);assert.equal(fs.existsSync(path.join(root,'public/css/dashboard.css')),false)})
test('hero contains five photographic frames',()=>{const h=read('index.html');assert.equal((h.match(/<figure class="hero-slide/g)||[]).length,5);assert.match(h,/images\.unsplash\.com\/photo-1475518845976-0fd87b7e4e5d/);assert.match(h,/commons\.wikimedia\.org\/wiki\/Special:Redirect\/file/);assert.match(h,/esrs\.jsc\.nasa\.gov/);assert.doesNotMatch(h,/earth-horizon\.svg|earth-night-aurora\.svg|moon-deep-space\.svg/)});

test('satellite catalog is a first-class desktop and mobile destination',()=>{const h=read('satellites.html'),j=read('public/js/satellites.js');assert.match(h,/Satellites/);assert.match(h,/dashboard\.html/);assert.match(j,/CelesTrak/);assert.match(j,/sessionStorage/);assert.match(j,/FOLLOW ON GLOBE/)});
test('globe keeps core physical layers enabled without optional layer switches',()=>{const h=read('dashboard.html'),j=read('public/js/globe.js');assert.match(h,/OBSERV/);assert.doesNotMatch(h,/data-layer="clouds"|data-layer="night"|data-layer="stars"/);assert.doesNotMatch(j,/\bnight\s*=/);assert.doesNotMatch(j,/night\.material/);assert.doesNotMatch(j,/earth_lights_2048\.png/);assert.match(j,/clouds\.rotation/);assert.match(j,/stars\.rotation/);assert.match(j,/sunMesh/)});
test('observatory sector documentation and branding are present',()=>{for(const p of ['index.html','about.html','data-policy.html','privacy.html','terms.html']){const h=read(p);assert.match(h,/3D Earth by Perez/)}const h=read('data-policy.html');for(const term of ['climate','air-quality','freshwater','wildfires'])assert.match(h,new RegExp(term,'i'))});

test('shared navigation is compact, persistent, and limits mobile links to four essentials',()=>{const n=read('public/js/navigation.js'),c=read('public/css/mobile-nav.css');assert.match(n,/global-open-globe/);assert.match(n,/const MOBILE=PAGES\.slice\(0,4\)/);assert.match(n,/aria-current/);assert.match(c,/\.site-nav-cluster/);assert.match(c,/grid-template-columns:repeat\(4/);assert.doesNotMatch(n,/PRIVACY|TERMS/)});
test('globe rendering tolerates missing Earth textures and location remains optional',()=>{const j=read('public/js/globe.js'),h=read('dashboard.html');assert.match(j,/loadTextureSafe/);assert.match(j,/fallbackTexture/);assert.match(j,/openLocationDialog/);assert.match(h,/id="location-dialog"/);assert.match(h,/id="confirm-location"/);assert.match(j,/location permission is not required/)});
test('satellite preview has a sized renderer viewport',()=>{const h=read('satellites.html'),c=read('public/css/satellites.css');assert.match(h,/id="sat-visual" class="sat-visual"/);assert.match(c,/#sat-visual,.sat-visual/)});
test('map has a CDN fallback and remains usable without geolocation',()=>{const h=read('map.html'),loader=read('public/js/map-loader.js'),s=read('public/js/map.js');assert.match(h,/map-loader\.js/);assert.match(loader,/unpkg\.com/);assert.match(s,/initFallbackMap/);assert.match(s,/tile\.openstreetmap\.org/);assert.match(s,/The map remains available/)});

test('satellite catalog initializes independently from WebGL and offers a 2D fallback',()=>{const j=read('public/js/satellites.js');assert.match(j,/renderPreviewFallback/);assert.match(j,/Three\.js library did not load/);assert.match(j,/Promise\.allSettled/);assert.match(j,/loadISSPreview\(\)\}catch/);});
test('map loader times out stalled OpenLayers CDNs and starts map fallback without Leaflet',()=>{const l=read('public/js/map-loader.js'),m=read('public/js/map.js');assert.match(l,/setTimeout/);assert.match(l,/4500/);assert.match(m,/new ol\.Map/);assert.match(m,/initFallbackMap/);assert.doesNotMatch(l+m,/leaflet/i);});
test('astronomical clock exposes place, ISP estimate, altitude, and coordinates',()=>{const h=read('dashboard.html'),j=read('public/js/globe.js'),g=read('src/routes/geocode.js');for(const id of ['observer-place','observer-isp','observer-altitude','observer-astro-coordinates'])assert.ok(h.includes(id),id);assert.match(j,/updateObserverDetails/);assert.match(g,/router\.get\('\/network'/);assert.match(g,/ipwho\.is/);});
test('light-content pages receive a high-contrast shared navigation treatment',()=>{const n=read('public/js/navigation.js'),c=read('public/css/mobile-nav.css');assert.match(n,/light-content-page/);assert.match(c,/\.light-content-page \.global-site-nav a\{color:#23364a\}/);});

test('database-backed observation layers are served and rendered on globe and map',()=>{
 const api=read('src/routes/api.js'),g=read('public/js/globe.js'),h=read('dashboard.html'),m=read('public/js/map.js');
 assert.ok(api.includes("router.get('/observatory/layers'"));assert.ok(api.includes('observatory_observations'));assert.ok(api.includes("supabaseQuery('earth_events'"));assert.ok(h.includes('data-sector="earthquakes"'));assert.ok(api.includes('limit=300'));assert.ok(g.includes('mergeDatabaseSatelliteCatalog'));assert.ok(read('public/js/satellites.js').includes('loadDatabaseCatalog'));assert.ok(read('satellites.html').includes('db-catalog-status'));
 assert.ok(g.includes('installObservatoryLayers'));assert.ok(g.includes('dataMarkerGroup'));assert.ok(g.includes('selectObservation'));
 assert.ok(h.includes('data-layer-drawer'));assert.ok(m.includes('loadObservatoryPoints'));assert.ok(m.includes('/api/observatory/layers'));
});
test('globe satellites are selectable and use SGP4-derived position and altitude',()=>{
 const g=read('public/js/globe.js');assert.ok(g.includes('Raycaster'));assert.ok(g.includes("kind:'satellite'"));
 assert.ok(g.includes('item._satrec'));assert.ok(g.includes('geo.height)/6371'));assert.ok(g.includes('nextState=satellite.propagate'));
});
test('mobile landing hero is decluttered and mobile navigation remains fixed while scrolling',()=>{
 const c=read('public/css/landing.css'),n=read('public/css/mobile-nav.css');
 assert.ok(c.includes('88dvh'));assert.ok(c.includes('max-width:36ch'));assert.ok(n.includes('position:fixed!important'));assert.ok(n.includes('bottom:0!important'));
});
